### PR TITLE
integration with cmake

### PR DESCRIPTION
**Pull request by callalilychen**
I did some change, so that it is possible to use it as cmake library using `FetchContent`

### CODE REVIEW

**Comment by andrew-hardin** [comment]
Thank you for the pull request. I appreciate that it brings the project together by supplying a default `git.cc` without touching the core script that's tracking the revision history.

Thus far, the project has remained version-free; the core script is intended to be downloaded and modified to fit the project. Allowing FetchContent integration would require(?) the project to be versioned so downstream projects can pin to a specific version (e.g. `GIT_TAG v1`). Does that sound right?

**Comment by wroyca** [comment]
Coming here to takes a look. 

> Thank you for the pull request. I appreciate that it brings the project together by supplying a default `git.cc` without touching the core script that's tracking the revision history.
> 
> Thus far, the project has remained version-free; the core script is intended to be downloaded and modified to fit the project. Allowing FetchContent integration would require(?) the project to be versioned so downstream projects can pin to a specific version (e.g. `GIT_TAG v1`). Does that sound right?

Hey @andrew-hardin, FetchContent can point to the master branch, making it unnecessary to use versioning on this project. If people want to point to a specific version, it is possible — and recommended — to use a git hash. I say this PR is pretty sweet and I'd love to see it merged at some point.✌

```
FetchContent_Declare(
  cmake_git_version_tracking
  GIT_REPOSITORY https://github.com/andrew-hardin/cmake-git-version-tracking
  GIT_TAG master
)
```

OR

```
FetchContent_Declare(
  cmake_git_version_tracking
  GIT_REPOSITORY https://github.com/andrew-hardin/cmake-git-version-tracking
  GIT_TAG 0ef58f1ef2ee02371d3e5be43e6cc6bf4004d8a5
)
``

**Review by wroyca — COMMENTED** [review]
I think cmake_git_version_tracking would be more appropriate to stay consistent

**Comment by andrew-hardin** [comment]
I see the value in this- it's "batteries included" integration with open source projects that are internet connected during builds. I'll work to get a slightly modified copy if this PR merged in.

**Comment by andrew-hardin** [comment]
Closing because these changes were included in #43.

**Pull request closed without merging**
